#pragma once
#include <stdint.h>
#include <stdbool.h>
#include "sequent_i2c.h"

#define RTD_CHANNEL_NR_MIN   1
#define RTD_CHANNEL_NR_MAX   8

#define SLAVE_OWN_ADDRESS_BASE 0x40

enum
{
    RTD_VAL1_ADD = 0,
    RTD_VAL2_ADD = RTD_VAL1_ADD + 4,
    RTD_VAL3_ADD = RTD_VAL2_ADD + 4,
    RTD_VAL4_ADD = RTD_VAL3_ADD + 4,
    RTD_VAL5_ADD = RTD_VAL4_ADD + 4,
    RTD_VAL6_ADD = RTD_VAL5_ADD + 4,
    RTD_VAL7_ADD = RTD_VAL6_ADD + 4,
    RTD_VAL8_ADD = RTD_VAL7_ADD + 4,

    DIAG_TEMPERATURE_MEM_ADD = RTD_VAL8_ADD + 4,
    DIAG_5V_MEM_ADD,

    I2C_MEM_WDT_RESET_ADD = DIAG_5V_MEM_ADD + 2,
    I2C_MEM_WDT_INTERVAL_SET_ADD,
    I2C_MEM_WDT_INTERVAL_GET_ADD = I2C_MEM_WDT_INTERVAL_SET_ADD + 2,
    I2C_MEM_WDT_INIT_INTERVAL_SET_ADD = I2C_MEM_WDT_INTERVAL_GET_ADD + 2,
    I2C_MEM_WDT_INIT_INTERVAL_GET_ADD = I2C_MEM_WDT_INIT_INTERVAL_SET_ADD + 2,
    I2C_MEM_WDT_RESET_COUNT_ADD = I2C_MEM_WDT_INIT_INTERVAL_GET_ADD + 2,
    I2C_MEM_WDT_CLEAR_RESET_COUNT_ADD = I2C_MEM_WDT_RESET_COUNT_ADD + 2,
    I2C_MEM_WDT_POWER_OFF_INTERVAL_SET_ADD,
    I2C_MEM_WDT_POWER_OFF_INTERVAL_GET_ADD = I2C_MEM_WDT_POWER_OFF_INTERVAL_SET_ADD + 4,

    REVISION_HW_MAJOR_MEM_ADD = I2C_MEM_WDT_POWER_OFF_INTERVAL_GET_ADD + 4,
    REVISION_HW_MINOR_MEM_ADD,
    REVISION_MAJOR_MEM_ADD,
    REVISION_MINOR_MEM_ADD,

    RTD_RES1_ADD,
    RTD_RES2_ADD = RTD_RES1_ADD + 4,
    RTD_RES3_ADD = RTD_RES2_ADD + 4,
    RTD_RES4_ADD = RTD_RES3_ADD + 4,
    RTD_RES5_ADD = RTD_RES4_ADD + 4,
    RTD_RES6_ADD = RTD_RES5_ADD + 4,
    RTD_RES7_ADD = RTD_RES6_ADD + 4,
    RTD_RES8_ADD = RTD_RES7_ADD + 4,

    RTD_REINIT_COUNT = RTD_RES8_ADD + 4,
    RTD_SPS1_ADD = RTD_REINIT_COUNT + 4,
    RTD_SPS2_ADD = RTD_SPS1_ADD + 2,
    RTD_CARD_TYPE = RTD_SPS2_ADD + 2,
    RTD_RASP_VOLT,

    I2C_MODBUS_SETINGS_ADD = RTD_RASP_VOLT + 2,   // 5 bytes

    RTD_LEDS_FUNC = I2C_MODBUS_SETINGS_ADD + 5,   // 2 bytes

    RTD_LED_THRESHOLD1 = RTD_LEDS_FUNC + 2,
    RTD_LED_THRESHOLD2 = RTD_LED_THRESHOLD1 + 2,
    RTD_LED_THRESHOLD3 = RTD_LED_THRESHOLD2 + 2,
    RTD_LED_THRESHOLD4 = RTD_LED_THRESHOLD3 + 2,
    RTD_LED_THRESHOLD5 = RTD_LED_THRESHOLD4 + 2,
    RTD_LED_THRESHOLD6 = RTD_LED_THRESHOLD5 + 2,
    RTD_LED_THRESHOLD7 = RTD_LED_THRESHOLD6 + 2,
    RTD_LED_THRESHOLD8 = RTD_LED_THRESHOLD7 + 2,

    I2C_CALIB_RES = RTD_LED_THRESHOLD8 + 2,   // float
    I2C_CALIB_CH  = I2C_CALIB_RES + 4,        // uint8_t
    I2C_SENSORS_TYPE,
    I2C_MEM_ADS_SAMPLE_SWITCH,                // uint16_t

};

class SM_RTD
{
public:
    SM_RTD(uint8_t stack = 0);

    bool begin();
    bool isAlive();

    float readTemp(uint8_t channel);
    float readRes(uint8_t channel);

private:
    uint8_t _hwAdd;
    bool    _detected;

    int writeByte(uint8_t reg, uint8_t value);
    int readByte(uint8_t reg, uint8_t *value);
    int readFloat(uint8_t reg, float *value);
};
